[build]
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
included_files = ["content/dist/**"]

[[redirects]]
from = "/api/survey/story"
to = "https://election-pakapas-survey.vercel.app/api/survey/story"
status = 200

[[redirects]]
from = "/api/survey/og"
to = "https://election-pakapas-survey.vercel.app/api/survey/og"
status = 200